---
- name: spine switches
  hosts: spines
  gather_facts: no
  vars:
    ops_system_hostname: "{{ inventory_hostname }}"
    ansible_user: admin
  roles:
    - role: switch
      ops_intf_admin_state: up

- name: fabric switches
  hosts: fabs
  gather_facts: yes
  vars:
    ops_system_hostname: "{{ inventory_hostname }}"
    ansible_user: admin
  roles:
    - role: switch
      ops_intf_admin_state: up

- name: edge switches
  hosts: edges
  gather_facts: yes
  vars:
    ops_system_hostname: "{{ inventory_hostname }}"
    ansible_user: admin
  roles:
    - role: switch
      ops_intf_admin_state: up
