---
- name: check the switch version
  hosts: switches
  gather_facts: yes
  vars:
    ops_debug: no
    expected: OpenSwitch
  tasks:
    - include: tasks/cli/check_version.yaml

- name: L2/L3 configuration on fabric switches
  hosts: fabrics
  gather_facts: no
  vars:
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: up

- name: L2/L3 configuration on spine switches
  hosts: spines
  gather_facts: no
  vars:
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: up

- name: L2/L3 configuration on leaf switches
  hosts: leaves
  gather_facts: no
  vars:
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: up

- name: check the switch hostname
  hosts: switches
  gather_facts: no
  vars:
    ops_debug: no
  tasks:
    - include: tasks/cli/check_hostname.yaml

- name: BGP configuration on fabric switches
  hosts: fabrics
  gather_facts: no
  vars:
    ops_debug: no
  roles:
    - { role: bgp, tags: [ bgp ] }

- name: BGP configuration on spine switches
  hosts: spines
  gather_facts: no
  vars:
    ops_debug: no
  roles:
    - { role: bgp, tags: [ bgp ] }

- name: BGP configuration on leaf switches
  hosts: leaves
  gather_facts: no
  vars:
    ops_debug: no
  roles:
    - { role: bgp, tags: [ bgp ] }

- name: check the switch configuration
  hosts: switches
  gather_facts: no
  vars:
    ops_debug: yes
  tasks:
    - include: tasks/check_running_config.yaml

- name: wait for BGP peering up
  hosts: switches
  gather_facts: no
  tasks:
    - pause: seconds=60
      tags: [ bgp ]

- name: check the BGP peering
  hosts: switches
  gather_facts: no
  vars:
    ops_debug: no
  tasks:
    - name: show ip bgp neighbors
      tags: [ bgp ]
      ops_command:
        commands:
          - show ip bgp neighbors
        provider: "{{ ops_provider }}"
        waitfor:
          - "result[0] contains 'state: Established'"
        interval: 1
        retries: 2
      register: result
      connection: local
    - name: print out the result
      tags: [ bgp ]
      debug: var=result

- name: check the IP routing table (RIB)
  hosts: switches
  gather_facts: yes
  vars:
    ops_debug: no
  tasks:
    - name: show ip route
      tags: [ bgp ]
      ops_command:
        commands:
          - show ip route
        provider: "{{ ops_provider }}"
        waitfor:
          - "result[0] contains '172.16.0.0/24'"
          - "result[0] contains '172.16.1.0/24'"
          - "result[0] contains '172.16.2.0/24'"
          - "result[0] contains '172.16.11.0/24'"
          - "result[0] contains '172.16.12.0/24'"
          - "result[0] contains '172.16.13.0/24'"
          - "result[0] contains '172.16.21.0/24'"
          - "result[0] contains '172.16.22.0/24'"
          - "result[0] contains '172.16.23.0/24'"
          - "result[0] contains '172.16.30.0/24'"
          - "result[0] contains '172.16.40.0/24'"
          - "result[0] contains '172.16.50.0/24'"
        interval: 1
        retries: 2
      register: result
      connection: local
    - name: print out the result
      tags: [ bgp ]
      debug: var=result
