---
- name: fabric switches
  hosts: fabrics
  gather_facts: yes
  vars:
    ansible_user: admin
    ops_system_hostname: "{{ inventory_hostname }}"
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: up

- name: spine switches
  hosts: spines
  gather_facts: yes
  vars:
    ansible_user: admin
    ops_system_hostname: "{{ inventory_hostname }}"
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: up

- name: leaf switches
  hosts: leaves
  gather_facts: yes
  vars:
    ansible_user: admin
    ops_system_hostname: "{{ inventory_hostname }}"
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: up
