---
- name: copy ssh public key to the switches
  hosts: switches
  gather_facts: no
  vars:
    ansible_user: root
    public_key: ~/.ssh/id_rsa.pub
  tasks:
    - authorized_key: user=admin key="{{ lookup('file', public_key) }}"

- name: spine switches
  hosts: spines
  gather_facts: yes
  vars:
    ansible_user: admin
    ops_system_hostname: "{{ inventory_hostname }}"
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: down

- name: fabric switches
  hosts: fabs
  gather_facts: yes
  vars:
    ansible_user: admin
    ops_system_hostname: "{{ inventory_hostname }}"
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: down

- name: edge switches
  hosts: edges
  gather_facts: yes
  vars:
    ansible_user: admin
    ops_system_hostname: "{{ inventory_hostname }}"
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: down
