---
- name: check the switch version
  hosts: switches
  gather_facts: yes
  vars:
    ops_debug: no
    expected: OpenSwitch
  tasks:
    - include: tasks/cli/check_version.yaml

- name: L2/L3 configuration on fabric switches
  hosts: fabrics
  gather_facts: no
  vars:
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: up

- name: L2/L3 configuration on spine switches
  hosts: spines
  gather_facts: no
  vars:
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: up

- name: L2/L3 configuration on leaf switches
  hosts: leaves
  gather_facts: no
  vars:
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: up

- name: check the switch hostname
  hosts: switches
  gather_facts: no
  vars:
    ops_debug: no
  tasks:
    - include: tasks/cli/check_hostname.yaml

- name: check the switch configuration
  hosts: switches
  gather_facts: no
  vars:
    ops_debug: yes
  tasks:
    - include: tasks/cli/check_running_config.yaml

- include: bgp.yaml
  tags: [ bgp ]
