---
- name: verify the switch version
  hosts: switches
  gather_facts: no
  vars:
    ansible_user: admin
    ops_debug: no
    cli:
      username: "{{ ops_username }}"
      password: "{{ ops_password }}"
      host: "{{ ansible_host }}"
      port: "{{ ansible_port }}"
  tasks:
    - name: show version CLI
      ops_command:
        commands:
          - show version
        provider: "{{ cli }}"
        waitfor:
          - "result[0] contains OpenSwitch"
        interval: 1
        retries: 2
      register: result
      connection: local
    - name: debug the result
      debug: var=result
      when: ops_debug

- name: basic L2/L3 for fabric switches
  hosts: fabrics
  gather_facts: yes
  vars:
    ansible_user: admin
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: up

- name: basic L2/L3 for spine switches
  hosts: spines
  gather_facts: yes
  vars:
    ansible_user: admin
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: up

- name: basic L2/L3 for leaf switches
  hosts: leaves
  gather_facts: yes
  vars:
    ansible_user: admin
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: up

- name: BGP for fabric switches
  hosts: fabrics
  gather_facts: yes
  vars:
    ansible_user: admin
    ops_debug: no
  roles:
    - role: bgp

- name: BGP for spine switches
  hosts: spines
  gather_facts: yes
  vars:
    ansible_user: admin
    ops_debug: no
  roles:
    - role: bgp

- name: BGP for leaf switches
  hosts: leaves
  gather_facts: yes
  vars:
    ansible_user: admin
    ops_debug: no
  roles:
    - role: bgp

- name: verify the switch configuration
  hosts: switches
  gather_facts: no
  vars:
    ansible_user: admin
    ops_debug: no
    cli:
      username: "{{ ops_username }}"
      password: "{{ ops_password }}"
      host: "{{ ansible_host }}"
      port: "{{ ansible_port }}"
  tasks:
    - name: show running-config
      ops_command:
        commands:
          - show running-config
        provider: "{{ cli }}"
        waitfor:
          - "result[0] contains 'hostname {{ ops_system_hostname }}'"
        interval: 1
        retries: 2
      register: result
      connection: local
    - name: print out the result
      debug: var=result
