---
- name: check the switch version
  hosts: switches
  gather_facts: yes
  vars:
    ansible_user: admin
    ops_debug: no
    cli:
      username: "{{ ops_username }}"
      password: "{{ ops_password }}"
      host: "{{ ansible_host }}"
      port: "{{ ansible_port }}"
    expected: OpenSwitch
  tasks:
    - name: show version CLI
      ops_command:
        commands:
          - show version
        provider: "{{ cli }}"
        waitfor:
          - "result[0] contains {{ expected }}"
        interval: 1
        retries: 2
      register: result
      connection: local
    - name: debug the result
      debug: var=result
      when: ops_debug

- name: L2/L3 configuration on fabric switches
  hosts: fabrics
  gather_facts: no
  vars:
    ansible_user: admin
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: up

- name: L2/L3 configuration on spine switches
  hosts: spines
  gather_facts: no
  vars:
    ansible_user: admin
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: up

- name: L2/L3 configuration on leaf switches
  hosts: leaves
  gather_facts: no
  vars:
    ansible_user: admin
    ops_debug: no
  roles:
    - role: switch
      ops_intf_admin_state: up

- name: BGP configuration on fabric switches
  hosts: fabrics
  gather_facts: no
  vars:
    ansible_user: admin
    ops_debug: no
  roles:
    - role: bgp

- name: BGP configuration on spine switches
  hosts: spines
  gather_facts: no
  vars:
    ansible_user: admin
    ops_debug: no
  roles:
    - role: bgp

- name: BGP configuration on leaf switches
  hosts: leaves
  gather_facts: no
  vars:
    ansible_user: admin
    ops_debug: no
  roles:
    - role: bgp

- name: check the switch configuration
  hosts: switches
  gather_facts: no
  vars:
    ansible_user: admin
    ops_debug: no
    cli:
      username: "{{ ops_username }}"
      password: "{{ ops_password }}"
      host: "{{ ansible_host }}"
      port: "{{ ansible_port }}"
  tasks:
    - name: show running-config
      ops_command:
        commands:
          - show running-config
        provider: "{{ cli }}"
        waitfor:
          - "result[0] contains 'hostname {{ ops_system_hostname }}'"
        interval: 1
        retries: 2
      register: result
      connection: local
    - name: print out the result
      debug: var=result

- name: wait for BGP peering up
  hosts: switches
  gather_facts: no
  tasks:
    - pause: seconds=60

- name: check the BGP peering
  hosts: switches
  gather_facts: no
  vars:
    ansible_user: admin
    ops_debug: no
    cli:
      username: "{{ ops_username }}"
      password: "{{ ops_password }}"
      host: "{{ ansible_host }}"
      port: "{{ ansible_port }}"
  tasks:
    - name: show ip bgp neighbors
      ops_command:
        commands:
          - show ip bgp neighbors
        provider: "{{ cli }}"
        waitfor:
          - "result[0] contains 'state: Established'"
        interval: 1
        retries: 2
      register: result
      connection: local
    - name: print out the result
      debug: var=result

- name: verify IP routing table (RIB)
  hosts: switches
  gather_facts: yes
  vars:
    ansible_user: admin
    ops_debug: no
    cli:
      username: "{{ ops_username }}"
      password: "{{ ops_password }}"
      host: "{{ ansible_host }}"
      port: "{{ ansible_port }}"
  tasks:
    - name: show ip route
      ops_command:
        commands:
          - show ip route
        provider: "{{ cli }}"
        waitfor:
          - "result[0] contains '172.16.0.0/24'"
        interval: 1
        retries: 2
      register: result
      connection: local
    - name: print out the result
      debug: var=result
