---
- name: fabric switches
  hosts: fabrics
  gather_facts: yes
  vars:
    ansible_user: admin
    ops_debug: no

  tasks:
    - name: Show version
      ops_command:
        username: netop
        password: netop
        host: 172.16.128.2
        port: 10022
        commands:
          - show version
