---
- name: check hostname CLI output
  ops_command:
    commands:
      - show hostname
    provider: "{{ ops_provider }}"
    waitfor:
      - "result[0] contains '{{ ops_system_hostname }}'"
    interval: 1
    retries: 2
  register: result
  connection: local

- name: print the CLI output
  debug: var=result
  when: ops_debug
