---
- name: setup docker host
  hosts: docker
  gather_facts: no
  tasks:
    - name: copy docker-compose related files
      copy: src={{ item }} dest=~/{{ item }}
      with_items:
        - docker-compose.yaml
        - Dockerfile
        - ops-if-netns.sh
        - id_rsa.pub
    - name: build openswitch/genericx86-64 image based on utils/Dockerfile
      become: true
      command: docker-compose build
    - name: run all the container
      command: docker-compose up -d
    - name: setup network by utils/docker-network.sh
      script: docker-network.sh >> /tmp/docker-network.done creates=/tmp/docker-network.done
    - pause: seconds=5

- name: setup docker containers
  hosts: switches
  gather_facts: no
  vars:
    ansible_user: admin
  tasks:
    - name: let's check the reachability
      ping:
    - name: move all the interfaces to the right namespace
      become: true
      command: /home/admin/bin/ops-if-netns.sh > /tmp/ops-if-netns.done creates=/tmp/ops-if-netns.done
