---
- name: copy ssh public key to the switches
  hosts: switches
  gather_facts: no
  vars:
    ansible_user: root
    public_key: ~/.ssh/id_rsa.pub
  tasks:
    - authorized_key: user=admin key="{{ lookup('file', public_key) }}"

- name: check the admin account on the switch
  hosts: switches
  gather_facts: no
  vars:
    ansible_user: admin
  tasks:
    - ping:

- name: taking care of the network interfaces
  hosts: switches
  gather_facts: no
  become: true
  vars:
    ansible_user: admin
  tasks:
    - command: /home/admin/bin/ops-if-netns.sh
