---
- name: setup docker host
  hosts: vm
  gather_facts: no
  tasks:
    - name: copy docker-compose related files
      copy: src={{ item }} dest=~/{{ item }}
      with_items:
        - docker-compose.yaml
        - Dockerfile
        - ops-if-netns.sh
    - name: build docker image and create containers
      command: docker-compose build
    - name: compose docker containers
      command: docker-compose up -d
    - name: docker networking
      script: docker-network.sh >> /tmp/docker-network.done creates=/tmp/docker-network.done
    - pause: seconds=5

- name: setup docker containers
  hosts: switches
  gather_facts: no
  vars:
    ansible_user: admin
  tasks:
    - name: let's check the reachability
      ping:
    - name: move all the interfaces to the right namespace
      become: true
      command: /home/admin/bin/ops-if-netns.sh > /tmp/ops-if-netns.done creates=/tmp/ops-if-netns.done
