---
- name: setup docker host
  hosts: docker
  gather_facts: no
  vars:
    your_public_key: id_rsa.pub
    docker_compose_file: docker-compose6.yaml
    docker_network_file: docker-network6.sh
  tasks:
    - name: copy files needed to create OpenSwitch docker instance
      copy: src={{ item.src }} dest=~/{{ item.dst }}
      with_items:
        - { src: "{{ docker_compose_file }}", dst: docker-compose.yaml }
        - { src: Dockerfile, dst: Dockerfile }
        - { src: ops-if-netns.sh, dst: ops-if-netns.sh }
        - { src: "~/.ssh/{{ your_public_key}}", dst: "{{ your_public_key }}" }
    - name: install pip
      become: yes
      apt: name=python-pip state=present update_cache=no
    - name: install docker-compose
      become: yes
      pip: name=docker-compose state=present
    - name: build OpenSwitch docker image based on utils/Dockerfile
      become: yes
      command: docker-compose build
    - name: run all the container
      command: docker-compose up -d
    - name: setup network by utils/docker-network.sh
      vars:
        lock: /tmp/docker-network.done 
      script: >
        "{{ docker_network_file }}" >> "{{ lock }}" creates="{{ lock }}"

- name: setup docker containers
  hosts: switches
  gather_facts: no
  vars:
    ansible_user: admin
  tasks:
    - pause: seconds=10
    - name: check the reachability
      ping:
    - name: move all the interfaces to the right namespace
      become: yes
      command: /home/admin/bin/ops-if-netns.sh > /tmp/ops-if-netns.done creates=/tmp/ops-if-netns.done
