---
- name: setup docker host
  hosts: docker
  gather_facts: no
  vars:
    your_public_key: id_rsa.pub
    network_lock_file: /tmp/docker-network.done
  tasks:
    - name: copy docker-compose related files
      copy: src={{ item }} dest=~/{{ item }}
      with_items:
        - docker-compose.yaml
        - Dockerfile
        - ops-if-netns.sh
    - name: copy your public key
      copy: src=~/.ssh/{{ your_public_key }} dest=~/{{ your_public_key }}
    - name: install pip
      become: yes
      apt: name=python-pip state=present
    - name: install docker-compose
      become: yes
      pip: name=docker-compose state=present
    - name: build openswitch/genericx86-64 image based on utils/Dockerfile
      become: yes
      command: docker-compose build
    - name: run all the container
      command: docker-compose up -d
    - name: setup network by utils/docker-network.sh
      script: docker-network.sh >> "{{ network_lock_file }}" creates=/tmp/docker-network.done
    - pause: seconds=5

- name: setup docker containers
  hosts: switches
  gather_facts: no
  vars:
    ansible_user: admin
  tasks:
    - name: let's check the reachability
      ping:
    - name: move all the interfaces to the right namespace
      become: true
      command: /home/admin/bin/ops-if-netns.sh > /tmp/ops-if-netns.done creates=/tmp/ops-if-netns.done
